version: '2.2'
services:
  web:
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}_web:${RELEASE_VERSION}
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
    ports:
      - "5000:5000"
    volumes:
      - ./src:/home/app/