version: '2.2'
services:
  web:
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}_web:${RELEASE_VERSION}
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/home/app/