version: '2.2'
services:
  proxy:
    container_name: ${PROJECT_NAME}_proxy
    image: ${PROJECT_NAME}_proxy:${RELEASE_VERSION}
    build: build/proxy
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - web
  web:
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}_web:${RELEASE_VERSION}
    build: build/web
    environment:
      - FLASK_PORT=${FLASK_PORT:-5000}
      - DATABASE_NAME=${DATABASE_NAME:-test.db}
    volumes:
      - ./src:/home/app/src
    depends_on:
      - db
    # ports:
    #   - "5001:5001"
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - flask-db-data:/var/lib/postgresql/data/pgdata
volumes:
  flask-db-data: